config/routes.rb
Moneyback::Application.routes.draw do
  resources :situations

  root :to => 'situations#index', :as => ""

end

app/models/situation.rb
# encoding: utf-8

class Situation < ActiveRecord::Base
  validates_presence_of :renda, :custo, :total_devedor, :fatura, :juros, :minimo_fatura, :message => "não pode estar em branco"
  
  validates_numericality_of :renda, :custo, :total_devedor, :fatura, :juros, :minimo_fatura, :allow_nil => true, :message => "deve ser um valor monetário"
end

app/controllers/application_controller.rb
# encoding: utf-8

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/situations_controller.rb
# encoding: utf-8

class SituationsController < ApplicationController
  # GET /situations
  # GET /situations.json
  def index
    @situation = Situation.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @situations }
    end
  end
  
  def create
    @situation = Situation.new(params[:situation])
    
    respond_to do |format|
      if @situation.save
      
        # Valor restante para quitar a dívida
        @valor_disponivel = @situation.renda - @situation.custo
        if @valor_disponivel <= 0
        	format.html { render "problem" }
        end
        
        # Calcula a sua dívida (divida passada + fatura desse mes)
        @divida = (@situation.total_devedor) * (1+(@situation.juros/100)) + @situation.fatura
        
        # Verifica se você consegue pagar a dívida em apenas 1 mês
        if @divida > @valor_disponivel
          format.html { render "multiple_months" }
        else
          format.html { render "single_month" }
        end
        
      else
        format.html { render action: "index" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moneyback</title>
    <%= stylesheet_link_tag :scaffold %>
    <%= csrf_meta_tag %>
  </head>
  <body>

    <div id="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/situations/_form.html.erb
<%= form_for(@situation) do |f| %>
  <% if @situation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@situation.errors.count, "erro") %> no formulário proíbem de avaliarmos a sua dívida:</h2>

      <ul>
      <% @situation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :renda, "Renda Disponível" %><br />
    R$ <%= f.text_field :renda %>
  </div>
  <div class="field">
    <%= f.label :custo, "Custos Fixos" %><br />
    R$ <%= f.text_field :custo %>
  </div>
  <div class="field">
    <%= f.label :total_devedor, "Total da sua dívida com o Cartão" %><br />
    R$ <%= f.text_field :total_devedor %>
  </div>
  <div class="field">
    <%= f.label :fatura, "Fatura deste mês do cartão" %><br />
    R$ <%= f.text_field :fatura %>
  </div>
  <div class="field">
    <%= f.label :juros, "Juros do cartão" %><br />
    % <%= f.text_field :juros %>
  </div>
  <div class="field">
    <%= f.label :minimo_fatura, "Mínimo a ser pago pela fatura" %><br />
    R$ <%= f.text_field :minimo_fatura %>
  </div>
  <div class="actions">
    <%= f.submit "Calcular"%>
  </div>
<% end %>

app/views/situations/_situation.html.erb
<p id="notice"><%= notice %></p>

<h1>Sua situação é a seguinte:</h1>

<p>
  <b>Renda Disponível:</b>
  R$ <%= @situation.renda %>
</p>

<p>
  <b>Custos Fixos:</b>
  R$ <%= @situation.custo %>
</p>

<p>
  <b>Total da sua dívida com o Cartão:</b>
  R$ <%= @situation.total_devedor %>
</p>

<p>
  <b>Fatura deste mês do cartão:</b>
  R$ <%= @situation.fatura %>
</p>

<p>
  <b>Juros do cartão:</b>
  R$ <%= @situation.juros %>
</p>

<p>
  <b>Mínimo a ser pago pela fatura:</b>
  R$ <%= @situation.minimo_fatura %>
</p>

<hr>

app/views/situations/index.html.erb
<h1 class="title">MoneyBack!</h1>

<p class="pStart">Aqui você aprende a pagar a sua dívida de cartão de crédito em poucos passos.</p>

<p class="pStart">Preencha o formulário abaixo com a sua situação atual e nós daremos dicas para quitar a sua dívida.</p>

<%= render 'form' %>

app/views/situations/multiple_months.html.erb
<h1 class="title">MoneyBack!</h1>

<%= render 'situation' %>

<h1>Passo 1:</h1>
<p>
	Pare de realizar compras desnecessárias.<br />
	Tenha apenas os gastos fixos.
</p>

<h1>Passo 2:</h1>
<p>
	Pague o maior valor possível da sua dívida com o valor que você possui restante.<br />
	<b>Dívida:</b>
 	R$ <%= @divida %>
 	<br />
 	<b>Total a pagar:</b>
 	R$ <%= @valor_disponivel %>
</p>

<h1>Passo 3:</h1>
<p>
	Realize todos os passos novamente no próximo mês!<br />
</p>


<%= link_to 'Calcular outra situação', situations_path %>

app/views/situations/problem.html.erb
<h1 class="title">MoneyBack!</h1>

<%= render 'situation' %>

<h1>Passo 1:</h1>
<p>
	Pare de realizar compras desnecessárias.<br />
	Tenha apenas os gastos fixos.
</p>

<h1>Passo 2:</h1>
<p>
	Você tem um problema...<br />
	<br />
	Seus gastos fixo são maiores que a sua renda. Assim você não consegue acumular recursos para quitar a sua dívida.<br />
	Reduza seus gastos fixos ou aumente a sua renda e calcule novamente.
</p>


<%= link_to 'Calcular outra situação', situations_path %>

app/views/situations/single_month.html.erb
<h1 class="title">MoneyBack!</h1>

<%= render 'situation' %>

<h1>Passo 1:</h1>
<p>
	Pare de realizar compras desnecessárias.<br />
	Tenha apenas os gastos fixos.
</p>

<h1>Passo 2:</h1>
<p>
	Pague a sua dívida.<br />
	<b>Dívida:</b>
 	R$ <%= @divida %>
</p>

<h1>Passo 3:</h1>
<p>
	Se sobrar algum valor, guarde o valor restante em sua conta não contraia mais dívidas!<br />
</p>


<%= link_to 'Calcular outra situação', situations_path %>